name: robupy

channels:
  - opensourceeconomics
  - conda-forge

dependencies:
  - python=3.7
  - numpy
  - anaconda-client
  - conda-build
  - conda-verify
  - statsmodels
  - pytest
  - pytest-xdist
  - pytest-cov
  - pre-commit
  - scipy
  - sphinx
  - flake8
  - numba
  - pip
  - pip:
      - black
