name: Continuous Integration Workflow
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'

jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: robupy
          auto-update-conda: true
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Run pytest.
        shell: bash -l {0}
        run: pytest --cov-report=xml --cov=./

      - name: Upload coverage report.
        if: runner.os == 'Linux' && matrix.python-version == '3.7'
        uses: codecov/codecov-action@v1
        with:
          token: 199bca1b-7f11-4b59-9977-122dd4ca31ba

      - name: Run pre-commits.
        shell: bash -l {0}
        run: |
          pre-commit install -f --install-hooks
          pre-commit run --all-files
